name: "ArtemCRM"
on:
    push:
        branches:
            - actions-test

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Привет мир, меня зовут ${{vars.NAME}}"
            - name: Test
              run: |
                  if [["${{secrets.SECRET}}" == "123"]]; then
                    echo "Секрет совпадает"
                  fi
