name: "ArtemCRM"
on:
    push:
        branches:
            - actions-test

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Привет мир, меня зовут ${{vars.NAME}}"
